spring:
  datasource:
    username: eclesiaste
    password: password
    url: jdbc:postgresql://localhost:5432/lucienstore
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    #show-sql: true
    properties:
      hibernate:
        format-ql: true
  #file upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 4b59dfd8844f52
    password: 627b0dc4a1cdc7
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    restart:
      enabled: true

#Exception
server:
  error:
    include-message: always
    include-stacktrace: never

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html

